//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDEN_COMPRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATOS_COMPRA()
        {
            this.INCLUYE = new HashSet<INCLUYE>();
        }
    
        public string nro_orden_compra { get; set; }
        public string RUC_cliente { get; set; }
        public string RUC_proveedor { get; set; }
        public string moneda { get; set; }
        public string solicitante { get; set; }
        public string obra { get; set; }
        public string orden_de_taller { get; set; }
        public string representante { get; set; }
        public string prioridad_compra { get; set; }
        public string autorizante { get; set; }
        public string requerimiento { get; set; }
        public string metodo_de_pago { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> SubtoTal_T { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual PAGO PAGO { get; set; }
        public virtual ENCARGADO ENCARGADO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCLUYE> INCLUYE { get; set; }
    }
}
