//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDEN_COMPRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCARGADO()
        {
            this.DATOS_COMPRA = new HashSet<DATOS_COMPRA>();
        }
    
        public string RUC_cliente { get; set; }
        public string nombre_Empresa { get; set; }
        public string padron { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATOS_COMPRA> DATOS_COMPRA { get; set; }
    }
}
