//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDEN_COMPRA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OCEntities : DbContext
    {
        public OCEntities()
            : base("name=OCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<DATOS_COMPRA> DATOS_COMPRA { get; set; }
        public virtual DbSet<ENCARGADO> ENCARGADO { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<INCLUYE> INCLUYE { get; set; }
    
        public virtual ObjectResult<string> sp_ordenCompra_entre_fecha(Nullable<System.DateTime> limteInf, Nullable<System.DateTime> limteSup)
        {
            var limteInfParameter = limteInf.HasValue ?
                new ObjectParameter("limteInf", limteInf) :
                new ObjectParameter("limteInf", typeof(System.DateTime));
    
            var limteSupParameter = limteSup.HasValue ?
                new ObjectParameter("limteSup", limteSup) :
                new ObjectParameter("limteSup", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ordenCompra_entre_fecha", limteInfParameter, limteSupParameter);
        }
    }
}
